### ISSUE TITLE
Pending `csr` after a few days deployment

### ISSUE THREAD

**Issue by e-minguez** [openshift-kni/install-scripts#97]
After a successful deployment using the install-scripts, `csr`s are not signed automatically:

```
$ oc logs metal3-7f8c7878df-8nlj7 -c metal3-ipa-downloader
Error from server: Get https://10.19.138.12:10250/containerLogs/openshift-machine-api/metal3-7f8c7878df-8nlj7/metal3-ipa-downloader: remote error: tls: internal error

$ oc get csr | head
NAME        AGE     REQUESTOR                                                CONDITION
csr-26tlc   39m     system:node:kni1-master-2.env.mydomain.example.com   Pending
csr-289tn   15h     system:node:kni1-master-1.env.mydomain.example.com   Pending
csr-28fbw   85m     system:node:kni1-master-1.env.mydomain.example.com   Pending
csr-28n94   170m    system:node:kni1-master-0.env.mydomain.example.com   Pending
csr-2j967   15h     system:node:kni1-master-0.env.mydomain.example.com   Pending
csr-2jzlt   10h     system:node:kni1-master-2.env.mydomain.example.com   Pending
csr-2qfwz   23h     system:node:kni1-master-0.env.mydomain.example.com   Pending
csr-2qjhz   13h     system:node:kni1-master-2.env.mydomain.example.com   Pending
csr-2xfq9   15h     system:node:kni1-master-2.env.mydomain.example.com   Pending

$ oc get nodes
NAME                                         STATUS   ROLES           AGE     VERSION
kni1-master-0.env.mydomain.example.com   Ready    master,worker   2d19h   v1.14.0+21f1332e6
kni1-master-1.env.mydomain.example.com   Ready    master,worker   2d19h   v1.14.0+21f1332e6
kni1-master-2.env.mydomain.example.com   Ready    master,worker   2d19h   v1.14.0+21f1332e6

$ oc get csr | wc -l
281
```

**Comment by hardys** [comment]
Can you confirm you have the fix_certs cron job running ref https://github.com/openshift-metal3/dev-scripts/pull/782?

**Comment by e-minguez** [comment]
What about an 'in cluster' solution like https://github.com/openshift-metal3/dev-scripts/pull/713/files ?

**Comment by karmab** [comment]
https://github.com/openshift-metal3/dev-scripts/pull/802 updated PR

**Comment by russellb** [comment]
I would suggest not using the cron job here (in install-scripts).  We should aim to keep the design goal of not relying on the provisioning host post-install.

An in cluster solution would be best here until it's no longer necessary.

https://bugzilla.redhat.com/show_bug.cgi?id=1737611 tracks some work that should resolve this for us.

**Comment by e-minguez** [comment]
@karmab do you mind to create a PR to incorporate https://github.com/openshift-metal3/dev-scripts/pull/802 here? Thanks.

**Comment by sreichar** [comment]
I had 2 clusters running for the weekend, and am no longer seeing and CSR pending.

Is anyone else still seeing this issue?
